version: '3.9'
 
volumes:
  test_logs:
    external:
      name: test_logs
       
services:


  ubuntu_auth:
    image: ubuntu_auth
    container_name: ubuntu_auth
    networks:
      network_fastapi:
        ipv4_address: 172.22.0.3
    environment:
      - LOG=1
    volumes:
      - test_logs:/home/tests
        
  ubuntu_perm:
    image: ubuntu_perm
    container_name: ubuntu_perm
    networks:
      network_fastapi:
        ipv4_address: 172.22.0.4
    environment:
      - LOG=1
    volumes:
      - test_logs:/home/tests

  ubuntu_content:
    image: ubuntu_content
    container_name: ubuntu_content
    networks:
      network_fastapi:
        ipv4_address: 172.22.0.5
    environment:
      - LOG=1
    volumes:
      - test_logs:/home/tests
networks:
  network_fastapi:
    external: true 
    
    
    

